import "./globals.css";
import type { Metadata } from "next";
import SessionProvider from "./components/SessionProvider";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Hotelmode",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
